// Generated by Apple Swift version 3.0 (swiftlang-800.0.46.2 clang-800.0.38)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if defined(__has_feature) && __has_feature(modules)
@import QuartzCore;
@import CoreGraphics;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import AVFoundation;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"

@interface CABasicAnimation (SWIFT_EXTENSION(WWZSwift))
@end

@class UIColor;

@interface CALayer (SWIFT_EXTENSION(WWZSwift))
- (void)wwz_setCornerWithRadius:(CGFloat)radius;
- (void)wwz_setCornerWithBorderWidth:(CGFloat)borderWidth borderColor:(UIColor * _Nullable)borderColor;
- (void)wwz_setCornerWithRadius:(CGFloat)radius borderWidth:(CGFloat)borderWidth borderColor:(UIColor * _Nullable)borderColor;
- (void)wwz_setShadowOffsetYWithShadowColor:(UIColor * _Nullable)shadowColor offsetY:(CGFloat)offsetY;
- (void)wwz_setShadowWithShadowColor:(UIColor * _Nullable)shadowColor offset:(CGSize)offset;
- (void)wwz_pauseAnimation;
- (void)wwz_resumeAnimation;
@end


@interface NSNotificationCenter (SWIFT_EXTENSION(WWZSwift))
+ (void)wwz_addObserver:(id _Nonnull)observer selector:(SEL _Nonnull)selector name:(NSString * _Nonnull)name;
+ (void)wwz_postWithName:(NSString * _Nonnull)name object:(id _Nullable)object;
+ (void)wwz_postWithName:(NSString * _Nonnull)name object:(id _Nullable)object userInfo:(NSDictionary * _Nullable)userInfo;
@end


@interface NSTimer (SWIFT_EXTENSION(WWZSwift))
@end


@interface UIAlertController (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithTitle:(NSString * _Nullable)title message:(NSString * _Nullable)message preferredStyle:(UIAlertControllerStyle)preferredStyle buttonTitles:(NSArray<NSString *> * _Nonnull)buttonTitles clickButtonAtIndexBlock:(void (^ _Nullable)(NSInteger))block;
@end


@interface UIBarButtonItem (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithImageName:(NSString * _Nonnull)imageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nonnull)nImageName hImageName:(NSString * _Nonnull)hImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nonnull)nImageName sImageName:(NSString * _Nonnull)sImageName;
@end

@class UIFont;

@interface UIButton (SWIFT_EXTENSION(WWZSwift))
/**
  设置title
*/
- (void)wwz_setTitleWithNTitle:(NSString * _Nullable)nTitle;
- (void)wwz_setTitleWithNTitle:(NSString * _Nullable)nTitle sTitle:(NSString * _Nullable)sTitle;
/**
  设置title color
*/
- (void)wwz_setTitleColorWithNColor:(UIColor * _Nullable)nColor;
- (void)wwz_setTitleColorWithSColor:(UIColor * _Nullable)sColor;
- (void)wwz_setTitleColorWithNColor:(UIColor * _Nullable)nColor hColor:(UIColor * _Nullable)hColor;
- (void)wwz_setTitleColorWithNColor:(UIColor * _Nullable)nColor sColor:(UIColor * _Nullable)sColor;
- (void)wwz_setTitleColorWithNColor:(UIColor * _Nullable)nColor hColor:(UIColor * _Nullable)hColor sColor:(UIColor * _Nullable)sColor;
/**
  设置image
*/
- (void)wwz_setNImage:(NSString * _Nullable)nImage hImage:(NSString * _Nullable)hImage sImage:(NSString * _Nullable)sImage;
/**
  设置image
*/
- (void)wwz_setNBImage:(NSString * _Nullable)nBImage hBImage:(NSString * _Nullable)hBImage sBImage:(NSString * _Nullable)sBImage;
/**
  方法
*/
- (void)wwz_setTarget:(id _Nullable)target action:(SEL _Nonnull)action;
/**
  左右间隔
*/
- (void)wwz_setLeftRightInset:(CGFloat)inset;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName hImageName:(NSString * _Nullable)hImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName sImageName:(NSString * _Nullable)sImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName hImageName:(NSString * _Nullable)hImageName sImageName:(NSString * _Nullable)sImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName nBImageName:(NSString * _Nullable)nBImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName hImageName:(NSString * _Nullable)hImageName nBImageName:(NSString * _Nullable)nBImageName hBImageName:(NSString * _Nullable)hBImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName sImageName:(NSString * _Nullable)sImageName nBImageName:(NSString * _Nullable)nBImageName sBImageName:(NSString * _Nullable)sBImageName;
- (nonnull instancetype)initWithNImageName:(NSString * _Nullable)nImageName hImageName:(NSString * _Nullable)hImageName sImageName:(NSString * _Nullable)sImageName nBImageName:(NSString * _Nullable)nBImageName hBImageName:(NSString * _Nullable)hBImageName sBImageName:(NSString * _Nullable)sBImageName;
- (nonnull instancetype)initWithFrame:(CGRect)frame nTitle:(NSString * _Nullable)nTitle titleFont:(UIFont * _Null_unspecified)titleFont nColor:(UIColor * _Nullable)nColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame nTitle:(NSString * _Nullable)nTitle sTitle:(NSString * _Nullable)sTitle titleFont:(UIFont * _Null_unspecified)titleFont nColor:(UIColor * _Nullable)nColor sColor:(UIColor * _Nullable)sColor;
- (nonnull instancetype)initWithFrame:(CGRect)frame nTitle:(NSString * _Nullable)nTitle sTitle:(NSString * _Nullable)sTitle titleFont:(UIFont * _Null_unspecified)titleFont nColor:(UIColor * _Nullable)nColor sColor:(UIColor * _Nullable)sColor nImageName:(NSString * _Nullable)nImageName sImageName:(NSString * _Nullable)sImageName;
@end


@interface UICollectionView (SWIFT_EXTENSION(WWZSwift))
@end


@interface UICollectionViewFlowLayout (SWIFT_EXTENSION(WWZSwift))
/**
  固定item count
*/
- (nonnull instancetype)initWithViewSize:(CGSize)viewSize sectionInset:(UIEdgeInsets)sectionInset itemCount:(NSInteger)itemCount lineSpace:(CGFloat)lineSpace itemSpace:(CGFloat)itemSpace scrollDirection:(UICollectionViewScrollDirection)scrollDirection;
/**
  固定itemSize
*/
- (nonnull instancetype)initWithSectionInset:(UIEdgeInsets)sectionInset itemSize:(CGSize)itemSize lineSpace:(CGFloat)lineSpace itemSpace:(CGFloat)itemSpace scrollDirection:(UICollectionViewScrollDirection)scrollDirection;
@end


@interface UIColor (SWIFT_EXTENSION(WWZSwift))
+ (UIColor * _Nonnull)colorFromRGBA:(CGFloat)r :(CGFloat)g :(CGFloat)b :(CGFloat)a;
+ (UIColor * _Nonnull)colorFromRGBAWithRgba:(NSUInteger)rgba;
@end


@interface UIImage (SWIFT_EXTENSION(WWZSwift))
/**
  图片不透明区渲染
*/
- (UIImage * _Nullable)wwz_imageMaskWithMaskColor:(UIColor * _Nonnull)maskColor;
@end


@interface UIImage (SWIFT_EXTENSION(WWZSwift))
/**
  压缩图片
*/
- (UIImage * _Nullable)wwz_compressedImageWithMaxFileSize:(NSInteger)maxFileSize;
- (NSData * _Nullable)wwz_compressedDataWithMaxFlieSize:(NSInteger)maxFlieSize;
@end


@interface UIImage (SWIFT_EXTENSION(WWZSwift))
/**
  从bundle中获取图片，imageName 需带后缀
*/
- (nullable instancetype)initWithImageName:(NSString * _Nonnull)imageName;
+ (UIImage * _Nullable)wwz_circleImageWithImageName:(NSString * _Nonnull)imageName borderWidth:(CGFloat)borderWidth borderColor:(UIColor * _Nonnull)borderColor;
/**
  背景转换成图片
*/
+ (UIImage * _Nullable)wwz_backgroundImageWithSize:(CGSize)size;
@end

@class CIImage;

@interface UIImage (SWIFT_EXTENSION(WWZSwift))
/**
  得到纯色图片
*/
+ (UIImage * _Nullable)wwz_imageWithColor:(UIColor * _Nonnull)color size:(CGSize)size;
/**
  虚线图片
*/
+ (UIImage * _Nullable)wwz_dashImageWithSize:(CGSize)size color:(UIColor * _Nonnull)color;
+ (UIImage * _Nullable)wwz_launchImageWithOrientation:(UIInterfaceOrientation)orientation;
/**
  通过图片Data数据第一个字节 来获取图片扩展名
*/
+ (NSString * _Nullable)wwz_contentTypeWithImageData:(NSData * _Nonnull)imageData;
/**
  由二维码生成图片
*/
+ (UIImage * _Nullable)wwz_imageWithQrcode:(NSString * _Nonnull)qrcode size:(CGSize)size;
/**
  将CIImage转换成UIImage
*/
+ (UIImage * _Nullable)wwz_imageWithCiimage:(CIImage * _Nonnull)ciimage size:(CGSize)size;
/**
  从图片中获取url
*/
+ (NSString * _Nullable)wwz_imageUrlStringWithImage:(UIImage * _Nullable)image;
@end


@interface UIImageView (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithImageName:(NSString * _Nonnull)imageName contentMode:(UIViewContentMode)contentMode;
- (nonnull instancetype)initWithFrame:(CGRect)frame imageName:(NSString * _Nonnull)imageName contentMode:(UIViewContentMode)contentMode;
@end


@interface UILabel (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithText:(NSString * _Nullable)text font:(UIFont * _Null_unspecified)font tColor:(UIColor * _Null_unspecified)tColor alignment:(NSTextAlignment)alignment numberOfLines:(NSInteger)numberOfLines;
- (nonnull instancetype)initWithFrame:(CGRect)frame text:(NSString * _Nullable)text font:(UIFont * _Null_unspecified)font tColor:(UIColor * _Null_unspecified)tColor alignment:(NSTextAlignment)alignment numberOfLines:(NSInteger)numberOfLines;
@end


@interface UINavigationBar (SWIFT_EXTENSION(WWZSwift))
@end


@interface UINavigationBar (SWIFT_EXTENSION(WWZSwift))
@end


@interface UINavigationBar (SWIFT_EXTENSION(WWZSwift))
/**
  设置标题
*/
- (void)wwz_setTitleWithColor:(UIColor * _Nonnull)color font:(UIFont * _Nonnull)font;
/**
  设置背景颜色
*/
- (void)wwz_setBackgroundColorWithBackgroundColor:(UIColor * _Nonnull)backgroundColor;
/**
  是否隐藏下面线
*/
- (void)wwz_setShadowImageWithIsHidden:(BOOL)isHidden;
/**
  还原，viewWillDisAppear调用
*/
- (void)wwz_reset;
/**
  设置tabbar内所有视图的alpha
*/
- (void)wwz_setElementsAlphaWithAlpha:(CGFloat)alpha;
@end


@interface UISlider (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithFrame:(CGRect)frame minImageName:(NSString * _Nonnull)minImageName maxImageName:(NSString * _Nonnull)maxImageName thumbImageName:(NSString * _Nonnull)thumbImageName;
- (nonnull instancetype)initWithFrame:(CGRect)frame minTrackImage:(UIImage * _Nullable)minTrackImage maxTrackImage:(UIImage * _Nullable)maxTrackImage thumbImage:(UIImage * _Nullable)thumbImage;
- (void)wwz_setEndTargetWithTarget:(id _Nullable)target action:(SEL _Nonnull)action;
- (void)wwz_setChangeTargetWithTarget:(id _Nullable)target action:(SEL _Nonnull)action;
@end


@interface UISwitch (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initOnTintColor:(UIColor * _Nullable)onTintColor tintColor:(UIColor * _Nullable)tintColor thumbTintColor:(UIColor * _Nullable)thumbTintColor;
- (void)wwz_setTargetWithTarget:(id _Nullable)target action:(SEL _Nonnull)action;
@end

@protocol UITableViewDataSource;
@protocol UITableViewDelegate;

@interface UITableView (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithFrame:(CGRect)frame dataSource:(id <UITableViewDataSource> _Nullable)dataSource delegate:(id <UITableViewDelegate> _Nullable)delegate;
@end


@interface UITextField (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithFrame:(CGRect)frame placeholder:(NSString * _Nullable)placeholder font:(UIFont * _Nullable)font;
@end


@interface UIView (SWIFT_EXTENSION(WWZSwift))
- (nonnull instancetype)initWithFrame:(CGRect)frame backgroundColor:(UIColor * _Nullable)backgroundColor;
@end


@interface UIView (SWIFT_EXTENSION(WWZSwift))
@property (nonatomic) CGFloat x;
@property (nonatomic) CGFloat y;
@property (nonatomic) CGFloat right;
@property (nonatomic) CGFloat bottom;
@property (nonatomic) CGPoint origin;
@property (nonatomic) CGSize size;
@property (nonatomic) CGFloat width;
@property (nonatomic) CGFloat height;
@property (nonatomic) CGFloat centerX;
@property (nonatomic) CGFloat centerY;
- (void)wwz_alignCenter;
- (void)wwz_alignCenterX;
- (void)wwz_alignCenterY;
- (void)wwz_alignRightWithRightOffSet:(CGFloat)rightOffSet;
- (void)wwz_alignBottomWithBottomOffSet:(CGFloat)bottomOffSet;
@end

@class NSCoder;

SWIFT_CLASS("_TtC8WWZSwift9WWZButton")
@interface WWZButton : UIButton
@property (nonatomic) CGFloat spaceY;
- (void)layoutSubviews;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WWZSwift14WWZCaptureTool")
@interface WWZCaptureTool : NSObject
/**
  显示视频预览层
  @param layer super layer
*/
- (void)showPreviewLayerInLayer:(CALayer * _Nonnull)inLayer;
/**
  开始扫描
*/
- (void)startRunning;
/**
  停止扫描
*/
- (void)stopRunning;
/**
  手电简开关
*/
- (void)setIsTorchModeOnTorchModeOn:(BOOL)torchModeOn;
+ (BOOL)isCaptureDenyAuthorizationed;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class AVCaptureOutput;
@class AVCaptureConnection;

@interface WWZCaptureTool (SWIFT_EXTENSION(WWZSwift)) <AVCaptureMetadataOutputObjectsDelegate>
/**
  扫描成功调用
*/
- (void)captureOutput:(AVCaptureOutput * _Null_unspecified)captureOutput didOutputMetadataObjects:(NSArray * _Null_unspecified)metadataObjects fromConnection:(AVCaptureConnection * _Null_unspecified)connection;
@end


SWIFT_CLASS("_TtC8WWZSwift11WWZShowView")
@interface WWZShowView : UIView
@property (nonatomic) NSTimeInterval animateDuration;
@property (nonatomic, strong) UIColor * _Nonnull backColor;
@property (nonatomic) BOOL isTapEnabled;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)wwz_showWithCompletion:(void (^ _Nullable)(BOOL))completion;
/**
  隐藏
*/
- (void)wwz_dismissWithCompletion:(void (^ _Nullable)(BOOL))completion;
@end


SWIFT_CLASS("_TtC8WWZSwift12WWZInputView")
@interface WWZInputView : WWZShowView
- (nonnull instancetype)initWithTitle:(NSString * _Nonnull)title text:(NSString * _Nullable)text placeHolder:(NSString * _Nullable)placeHolder buttonTitles:(NSArray<NSString *> * _Nonnull)buttonTitles clickButtonAtIndex:(void (^ _Nonnull)(NSString * _Nonnull, NSInteger))block OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WWZInputView (SWIFT_EXTENSION(WWZSwift)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField;
@end


@interface WWZInputView (SWIFT_EXTENSION(WWZSwift))
@end


SWIFT_CLASS("_TtC8WWZSwift14WWZMenuPopover")
@interface WWZMenuPopover : UIView
@property (nonatomic) NSTimeInterval animateDuration;
@property (nonatomic) CGFloat cornerRadius;
@property (nonatomic) CGPoint anchorPoint;
@property (nonatomic) CGRect pointerFrame;
@property (nonatomic, strong) UIColor * _Nonnull anchorColor;
- (nonnull instancetype)initWithCellSize:(CGSize)cellSize titles:(NSArray<NSString *> * _Nonnull)titles imageNames:(NSArray<NSString *> * _Nullable)imageNames OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end


@interface WWZMenuPopover (SWIFT_EXTENSION(WWZSwift))
- (void)wwz_show;
- (void)wwz_dismiss;
@end

@class UITableViewCell;

@interface WWZMenuPopover (SWIFT_EXTENSION(WWZSwift)) <UITableViewDelegate, UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
- (CGFloat)tableView:(UITableView * _Nonnull)tableView heightForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end



@interface WWZShowView (SWIFT_EXTENSION(WWZSwift))
@end


SWIFT_CLASS("_TtC8WWZSwift15WWZSiriWaveView")
@interface WWZSiriWaveView : UIView
@property (nonatomic) NSUInteger numberOfWaves;
@property (nonatomic, strong) UIColor * _Nonnull waveColor;
@property (nonatomic) CGFloat primaryWaveLineWidth;
@property (nonatomic) CGFloat secondaryWaveLineWidth;
@property (nonatomic) CGFloat idleAmplitude;
@property (nonatomic) CGFloat frequency;
@property (nonatomic) CGFloat amplitude;
@property (nonatomic) CGFloat density;
@property (nonatomic) CGFloat phaseShift;
- (void)updateWithLevel:(CGFloat)level;
- (void)drawRect:(CGRect)rect;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC8WWZSwift16WWZTableViewCell")
@interface WWZTableViewCell : UITableViewCell
/**
  sub label
*/
@property (nonatomic, strong) UILabel * _Nullable subLabel;
/**
  right label
*/
@property (nonatomic, strong) UILabel * _Nullable rightLabel;
/**
  switch
*/
@property (nonatomic, strong) UISwitch * _Nullable mySwitch;
/**
  text label 与 sub label 间距
*/
@property (nonatomic) CGFloat titleSpaceH;
/**
  是否为最后一行cell
*/
@property (nonatomic) BOOL isLastCell;
/**
  line
*/
@property (nonatomic, strong) UIView * _Nonnull lineView;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (nonnull instancetype)initWithStyle:(UITableViewCellStyle)style reuseIdentifier:(NSString * _Nullable)reuseIdentifier SWIFT_UNAVAILABLE;
@end


@interface WWZTableViewCell (SWIFT_EXTENSION(WWZSwift))
@end

@class NSAttributedString;

SWIFT_CLASS("_TtC8WWZSwift10WWZTipView")
@interface WWZTipView : WWZShowView
@property (nonatomic, strong) UIColor * _Nonnull buttonTitleColor;
@property (nonatomic, strong) UIFont * _Nonnull buttonTitleFont;
- (nonnull instancetype)initWithAttributedText:(NSAttributedString * _Nonnull)attributedText buttonTitles:(NSArray<NSString *> * _Nonnull)buttonTitles clickButtonAtIndex:(void (^ _Nonnull)(NSInteger))block OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


@interface WWZTipView (SWIFT_EXTENSION(WWZSwift))
@end

@class NSBundle;

SWIFT_CLASS("_TtC8WWZSwift17WWZViewController")
@interface WWZViewController : UIViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) UIInterfaceOrientation preferredInterfaceOrientationForPresentation;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
